"""Module containing city and region data for all countries."""

from dataclasses import dataclass


@dataclass(frozen=True)
class City:
    name: str
    country: str
    region: str
    latitude: float
    longitude: float
    is_capital: bool


@dataclass(frozen=True)
class Region:
    name: str
    country: str
    continent: str


REGIONS: list[Region] = [
    Region("Kabul Province", "Afghanistan", "Asia"),
    Region("Herat Province", "Afghanistan", "Asia"),
    Region("Kandahar Province", "Afghanistan", "Asia"),
    Region("Tirana County", "Albania", "Europe"),
    Region("Durres County", "Albania", "Europe"),
    Region("Algiers Province", "Algeria", "Africa"),
    Region("Oran Province", "Algeria", "Africa"),
    Region("Buenos Aires Province", "Argentina", "South America"),
    Region("Cordoba Province", "Argentina", "South America"),
    Region("Santa Fe Province", "Argentina", "South America"),
    Region("New South Wales", "Australia", "Oceania"),
    Region("Victoria", "Australia", "Oceania"),
    Region("Queensland", "Australia", "Oceania"),
    Region("Western Australia", "Australia", "Oceania"),
    Region("South Australia", "Australia", "Oceania"),
    Region("Tasmania", "Australia", "Oceania"),
    Region("Vienna", "Austria", "Europe"),
    Region("Salzburg", "Austria", "Europe"),
    Region("Tyrol", "Austria", "Europe"),
    Region("Dhaka Division", "Bangladesh", "Asia"),
    Region("Chittagong Division", "Bangladesh", "Asia"),
    Region("Brussels-Capital", "Belgium", "Europe"),
    Region("Flanders", "Belgium", "Europe"),
    Region("Wallonia", "Belgium", "Europe"),
    Region("Sao Paulo", "Brazil", "South America"),
    Region("Rio de Janeiro", "Brazil", "South America"),
    Region("Minas Gerais", "Brazil", "South America"),
    Region("Bahia", "Brazil", "South America"),
    Region("Amazonas", "Brazil", "South America"),
    Region("British Columbia", "Canada", "North America"),
    Region("Ontario", "Canada", "North America"),
    Region("Quebec", "Canada", "North America"),
    Region("Alberta", "Canada", "North America"),
    Region("Manitoba", "Canada", "North America"),
    Region("Saskatchewan", "Canada", "North America"),
    Region("Beijing", "China", "Asia"),
    Region("Shanghai", "China", "Asia"),
    Region("Guangdong", "China", "Asia"),
    Region("Sichuan", "China", "Asia"),
    Region("Zhejiang", "China", "Asia"),
    Region("Cundinamarca", "Colombia", "South America"),
    Region("Antioquia", "Colombia", "South America"),
    Region("Hovedstaden", "Denmark", "Europe"),
    Region("Midtjylland", "Denmark", "Europe"),
    Region("Cairo Governorate", "Egypt", "Africa"),
    Region("Alexandria Governorate", "Egypt", "Africa"),
    Region("Giza Governorate", "Egypt", "Africa"),
    Region("Uusimaa", "Finland", "Europe"),
    Region("Pirkanmaa", "Finland", "Europe"),
    Region("Ile-de-France", "France", "Europe"),
    Region("Provence-Alpes-Cote d'Azur", "France", "Europe"),
    Region("Auvergne-Rhone-Alpes", "France", "Europe"),
    Region("Nouvelle-Aquitaine", "France", "Europe"),
    Region("Occitanie", "France", "Europe"),
    Region("Bavaria", "Germany", "Europe"),
    Region("North Rhine-Westphalia", "Germany", "Europe"),
    Region("Baden-Wurttemberg", "Germany", "Europe"),
    Region("Lower Saxony", "Germany", "Europe"),
    Region("Hesse", "Germany", "Europe"),
    Region("Berlin", "Germany", "Europe"),
    Region("Attica", "Greece", "Europe"),
    Region("Central Macedonia", "Greece", "Europe"),
    Region("Maharashtra", "India", "Asia"),
    Region("Karnataka", "India", "Asia"),
    Region("Tamil Nadu", "India", "Asia"),
    Region("Delhi", "India", "Asia"),
    Region("Uttar Pradesh", "India", "Asia"),
    Region("West Bengal", "India", "Asia"),
    Region("Gujarat", "India", "Asia"),
    Region("Rajasthan", "India", "Asia"),
    Region("Kerala", "India", "Asia"),
    Region("Telangana", "India", "Asia"),
    Region("Jakarta", "Indonesia", "Asia"),
    Region("West Java", "Indonesia", "Asia"),
    Region("East Java", "Indonesia", "Asia"),
    Region("Bali", "Indonesia", "Asia"),
    Region("Tehran Province", "Iran", "Asia"),
    Region("Isfahan Province", "Iran", "Asia"),
    Region("Leinster", "Ireland", "Europe"),
    Region("Munster", "Ireland", "Europe"),
    Region("Tel Aviv District", "Israel", "Asia"),
    Region("Jerusalem District", "Israel", "Asia"),
    Region("Lazio", "Italy", "Europe"),
    Region("Lombardy", "Italy", "Europe"),
    Region("Campania", "Italy", "Europe"),
    Region("Tuscany", "Italy", "Europe"),
    Region("Veneto", "Italy", "Europe"),
    Region("Kanto", "Japan", "Asia"),
    Region("Kansai", "Japan", "Asia"),
    Region("Chubu", "Japan", "Asia"),
    Region("Kyushu", "Japan", "Asia"),
    Region("Tohoku", "Japan", "Asia"),
    Region("Nairobi County", "Kenya", "Africa"),
    Region("Mombasa County", "Kenya", "Africa"),
    Region("Seoul Capital Area", "South Korea", "Asia"),
    Region("Gyeongsang", "South Korea", "Asia"),
    Region("Mexico City", "Mexico", "North America"),
    Region("Jalisco", "Mexico", "North America"),
    Region("Nuevo Leon", "Mexico", "North America"),
    Region("State of Mexico", "Mexico", "North America"),
    Region("North Holland", "Netherlands", "Europe"),
    Region("South Holland", "Netherlands", "Europe"),
    Region("Utrecht", "Netherlands", "Europe"),
    Region("Auckland", "New Zealand", "Oceania"),
    Region("Wellington Region", "New Zealand", "Oceania"),
    Region("Canterbury", "New Zealand", "Oceania"),
    Region("Lagos State", "Nigeria", "Africa"),
    Region("Abuja Federal Capital Territory", "Nigeria", "Africa"),
    Region("Kano State", "Nigeria", "Africa"),
    Region("Oslo", "Norway", "Europe"),
    Region("Vestland", "Norway", "Europe"),
    Region("Punjab", "Pakistan", "Asia"),
    Region("Sindh", "Pakistan", "Asia"),
    Region("Islamabad Capital Territory", "Pakistan", "Asia"),
    Region("Lima Region", "Peru", "South America"),
    Region("Arequipa Region", "Peru", "South America"),
    Region("Metro Manila", "Philippines", "Asia"),
    Region("Cebu", "Philippines", "Asia"),
    Region("Masovian Voivodeship", "Poland", "Europe"),
    Region("Lesser Poland Voivodeship", "Poland", "Europe"),
    Region("Lisbon District", "Portugal", "Europe"),
    Region("Porto District", "Portugal", "Europe"),
    Region("Moscow Federal City", "Russia", "Europe"),
    Region("Saint Petersburg", "Russia", "Europe"),
    Region("Novosibirsk Oblast", "Russia", "Europe"),
    Region("Riyadh Region", "Saudi Arabia", "Asia"),
    Region("Makkah Region", "Saudi Arabia", "Asia"),
    Region("Eastern Region", "Saudi Arabia", "Asia"),
    Region("Gauteng", "South Africa", "Africa"),
    Region("Western Cape", "South Africa", "Africa"),
    Region("KwaZulu-Natal", "South Africa", "Africa"),
    Region("Community of Madrid", "Spain", "Europe"),
    Region("Catalonia", "Spain", "Europe"),
    Region("Andalusia", "Spain", "Europe"),
    Region("Valencia", "Spain", "Europe"),
    Region("Stockholm County", "Sweden", "Europe"),
    Region("Vastra Gotaland County", "Sweden", "Europe"),
    Region("Canton of Zurich", "Switzerland", "Europe"),
    Region("Canton of Bern", "Switzerland", "Europe"),
    Region("Canton of Geneva", "Switzerland", "Europe"),
    Region("Bangkok", "Thailand", "Asia"),
    Region("Chiang Mai Province", "Thailand", "Asia"),
    Region("Istanbul", "Turkey", "Asia"),
    Region("Ankara Province", "Turkey", "Asia"),
    Region("Izmir Province", "Turkey", "Asia"),
    Region("Kyiv Oblast", "Ukraine", "Europe"),
    Region("Lviv Oblast", "Ukraine", "Europe"),
    Region("Abu Dhabi", "United Arab Emirates", "Asia"),
    Region("Dubai", "United Arab Emirates", "Asia"),
    Region("Sharjah", "United Arab Emirates", "Asia"),
    Region("England", "United Kingdom", "Europe"),
    Region("Scotland", "United Kingdom", "Europe"),
    Region("Wales", "United Kingdom", "Europe"),
    Region("Northern Ireland", "United Kingdom", "Europe"),
    Region("California", "United States", "North America"),
    Region("Texas", "United States", "North America"),
    Region("New York", "United States", "North America"),
    Region("Florida", "United States", "North America"),
    Region("Illinois", "United States", "North America"),
    Region("Pennsylvania", "United States", "North America"),
    Region("Ohio", "United States", "North America"),
    Region("Georgia", "United States", "North America"),
    Region("Washington", "United States", "North America"),
    Region("Massachusetts", "United States", "North America"),
    Region("Montevideo Department", "Uruguay", "South America"),
    Region("Capital District", "Venezuela", "South America"),
    Region("Zulia", "Venezuela", "South America"),
    Region("Hanoi", "Vietnam", "Asia"),
    Region("Ho Chi Minh City", "Vietnam", "Asia"),
]


CITIES: list[City] = [
    City("Kabul", "Afghanistan", "Kabul Province", 34.53, 69.17, True),
    City("Herat", "Afghanistan", "Herat Province", 34.34, 62.20, False),
    City("Kandahar", "Afghanistan", "Kandahar Province", 31.61, 65.71, False),
    City("Tirana", "Albania", "Tirana County", 41.33, 19.82, True),
    City("Durres", "Albania", "Durres County", 41.32, 19.45, False),
    City("Algiers", "Algeria", "Algiers Province", 36.75, 3.04, True),
    City("Oran", "Algeria", "Oran Province", 35.70, -0.63, False),
    City("Buenos Aires", "Argentina", "Buenos Aires Province", -34.60, -58.38, True),
    City("Cordoba", "Argentina", "Cordoba Province", -31.42, -64.18, False),
    City("Rosario", "Argentina", "Santa Fe Province", -32.95, -60.65, False),
    City("Canberra", "Australia", "New South Wales", -35.28, 149.13, True),
    City("Sydney", "Australia", "New South Wales", -33.87, 151.21, False),
    City("Melbourne", "Australia", "Victoria", -37.81, 144.96, False),
    City("Brisbane", "Australia", "Queensland", -27.47, 153.03, False),
    City("Perth", "Australia", "Western Australia", -31.95, 115.86, False),
    City("Adelaide", "Australia", "South Australia", -34.93, 138.60, False),
    City("Hobart", "Australia", "Tasmania", -42.88, 147.33, False),
    City("Vienna", "Austria", "Vienna", 48.21, 16.37, True),
    City("Salzburg", "Austria", "Salzburg", 47.80, 13.04, False),
    City("Innsbruck", "Austria", "Tyrol", 47.26, 11.39, False),
    City("Dhaka", "Bangladesh", "Dhaka Division", 23.81, 90.41, True),
    City("Chittagong", "Bangladesh", "Chittagong Division", 22.36, 91.78, False),
    City("Brussels", "Belgium", "Brussels-Capital", 50.85, 4.35, True),
    City("Antwerp", "Belgium", "Flanders", 51.22, 4.40, False),
    City("Ghent", "Belgium", "Flanders", 51.05, 3.72, False),
    City("Charleroi", "Belgium", "Wallonia", 50.41, 4.44, False),
    City("Brasilia", "Brazil", "Sao Paulo", -15.79, -47.88, True),
    City("Sao Paulo", "Brazil", "Sao Paulo", -23.55, -46.63, False),
    City("Rio de Janeiro", "Brazil", "Rio de Janeiro", -22.91, -43.17, False),
    City("Salvador", "Brazil", "Bahia", -12.97, -38.51, False),
    City("Manaus", "Brazil", "Amazonas", -3.12, -60.02, False),
    City("Ottawa", "Canada", "Ontario", 45.42, -75.70, True),
    City("Toronto", "Canada", "Ontario", 43.65, -79.38, False),
    City("Vancouver", "Canada", "British Columbia", 49.28, -123.12, False),
    City("Montreal", "Canada", "Quebec", 45.50, -73.57, False),
    City("Calgary", "Canada", "Alberta", 51.05, -114.07, False),
    City("Edmonton", "Canada", "Alberta", 53.55, -113.49, False),
    City("Winnipeg", "Canada", "Manitoba", 49.90, -97.14, False),
    City("Beijing", "China", "Beijing", 39.90, 116.40, True),
    City("Shanghai", "China", "Shanghai", 31.23, 121.47, False),
    City("Guangzhou", "China", "Guangdong", 23.13, 113.26, False),
    City("Shenzhen", "China", "Guangdong", 22.54, 114.06, False),
    City("Chengdu", "China", "Sichuan", 30.57, 104.07, False),
    City("Hangzhou", "China", "Zhejiang", 30.27, 120.15, False),
    City("Bogota", "Colombia", "Cundinamarca", 4.71, -74.07, True),
    City("Medellin", "Colombia", "Antioquia", 6.25, -75.56, False),
    City("Copenhagen", "Denmark", "Hovedstaden", 55.68, 12.57, True),
    City("Aarhus", "Denmark", "Midtjylland", 56.15, 10.21, False),
    City("Cairo", "Egypt", "Cairo Governorate", 30.04, 31.24, True),
    City("Alexandria", "Egypt", "Alexandria Governorate", 31.20, 29.92, False),
    City("Giza", "Egypt", "Giza Governorate", 30.01, 31.21, False),
    City("Helsinki", "Finland", "Uusimaa", 60.17, 24.94, True),
    City("Tampere", "Finland", "Pirkanmaa", 61.50, 23.79, False),
    City("Paris", "France", "Ile-de-France", 48.86, 2.35, True),
    City("Marseille", "France", "Provence-Alpes-Cote d'Azur", 43.30, 5.37, False),
    City("Lyon", "France", "Auvergne-Rhone-Alpes", 45.76, 4.84, False),
    City("Toulouse", "France", "Occitanie", 43.60, 1.44, False),
    City("Bordeaux", "France", "Nouvelle-Aquitaine", 44.84, -0.58, False),
    City("Berlin", "Germany", "Berlin", 52.52, 13.41, True),
    City("Munich", "Germany", "Bavaria", 48.14, 11.58, False),
    City("Hamburg", "Germany", "North Rhine-Westphalia", 53.55, 9.99, False),
    City("Cologne", "Germany", "North Rhine-Westphalia", 50.94, 6.96, False),
    City("Frankfurt", "Germany", "Hesse", 50.11, 8.68, False),
    City("Stuttgart", "Germany", "Baden-Wurttemberg", 48.78, 9.18, False),
    City("Athens", "Greece", "Attica", 37.98, 23.73, True),
    City("Thessaloniki", "Greece", "Central Macedonia", 40.64, 22.94, False),
    City("New Delhi", "India", "Delhi", 28.61, 77.21, True),
    City("Mumbai", "India", "Maharashtra", 19.08, 72.88, False),
    City("Bangalore", "India", "Karnataka", 12.97, 77.59, False),
    City("Chennai", "India", "Tamil Nadu", 13.08, 80.27, False),
    City("Kolkata", "India", "West Bengal", 22.57, 88.36, False),
    City("Hyderabad", "India", "Telangana", 17.39, 78.49, False),
    City("Ahmedabad", "India", "Gujarat", 23.02, 72.57, False),
    City("Jaipur", "India", "Rajasthan", 26.91, 75.79, False),
    City("Kochi", "India", "Kerala", 9.93, 76.27, False),
    City("Lucknow", "India", "Uttar Pradesh", 26.85, 80.95, False),
    City("Jakarta", "Indonesia", "Jakarta", -6.21, 106.85, True),
    City("Surabaya", "Indonesia", "East Java", -7.25, 112.75, False),
    City("Bandung", "Indonesia", "West Java", -6.91, 107.61, False),
    City("Denpasar", "Indonesia", "Bali", -8.65, 115.22, False),
    City("Tehran", "Iran", "Tehran Province", 35.69, 51.39, True),
    City("Isfahan", "Iran", "Isfahan Province", 32.65, 51.68, False),
    City("Dublin", "Ireland", "Leinster", 53.35, -6.27, True),
    City("Cork", "Ireland", "Munster", 51.90, -8.47, False),
    City("Jerusalem", "Israel", "Jerusalem District", 31.77, 35.23, True),
    City("Tel Aviv", "Israel", "Tel Aviv District", 32.09, 34.78, False),
    City("Rome", "Italy", "Lazio", 41.90, 12.50, True),
    City("Milan", "Italy", "Lombardy", 45.46, 9.19, False),
    City("Naples", "Italy", "Campania", 40.85, 14.27, False),
    City("Florence", "Italy", "Tuscany", 43.77, 11.25, False),
    City("Venice", "Italy", "Veneto", 45.44, 12.34, False),
    City("Tokyo", "Japan", "Kanto", 35.68, 139.69, True),
    City("Osaka", "Japan", "Kansai", 34.69, 135.50, False),
    City("Nagoya", "Japan", "Chubu", 35.18, 136.91, False),
    City("Fukuoka", "Japan", "Kyushu", 33.59, 130.40, False),
    City("Sendai", "Japan", "Tohoku", 38.27, 140.87, False),
    City("Nairobi", "Kenya", "Nairobi County", -1.29, 36.82, True),
    City("Mombasa", "Kenya", "Mombasa County", -4.04, 39.67, False),
    City("Seoul", "South Korea", "Seoul Capital Area", 37.57, 126.98, True),
    City("Busan", "South Korea", "Gyeongsang", 35.18, 129.08, False),
    City("Mexico City", "Mexico", "Mexico City", 19.43, -99.13, True),
    City("Guadalajara", "Mexico", "Jalisco", 20.67, -103.35, False),
    City("Monterrey", "Mexico", "Nuevo Leon", 25.67, -100.31, False),
    City("Amsterdam", "Netherlands", "North Holland", 52.37, 4.90, True),
    City("Rotterdam", "Netherlands", "South Holland", 51.92, 4.48, False),
    City("The Hague", "Netherlands", "South Holland", 52.08, 4.30, False),
    City("Utrecht", "Netherlands", "Utrecht", 52.09, 5.12, False),
    City("Wellington", "New Zealand", "Wellington Region", -41.29, 174.78, True),
    City("Auckland", "New Zealand", "Auckland", -36.85, 174.76, False),
    City("Christchurch", "New Zealand", "Canterbury", -43.53, 172.64, False),
    City("Abuja", "Nigeria", "Abuja Federal Capital Territory", 9.06, 7.49, True),
    City("Lagos", "Nigeria", "Lagos State", 6.52, 3.38, False),
    City("Kano", "Nigeria", "Kano State", 12.00, 8.52, False),
    City("Oslo", "Norway", "Oslo", 59.91, 10.75, True),
    City("Bergen", "Norway", "Vestland", 60.39, 5.32, False),
    City("Islamabad", "Pakistan", "Islamabad Capital Territory", 33.69, 73.04, True),
    City("Karachi", "Pakistan", "Sindh", 24.86, 67.01, False),
    City("Lahore", "Pakistan", "Punjab", 31.55, 74.35, False),
    City("Lima", "Peru", "Lima Region", -12.05, -77.04, True),
    City("Arequipa", "Peru", "Arequipa Region", -16.41, -71.54, False),
    City("Manila", "Philippines", "Metro Manila", 14.60, 120.98, True),
    City("Cebu City", "Philippines", "Cebu", 10.31, 123.89, False),
    City("Warsaw", "Poland", "Masovian Voivodeship", 52.23, 21.01, True),
    City("Krakow", "Poland", "Lesser Poland Voivodeship", 50.06, 19.94, False),
    City("Lisbon", "Portugal", "Lisbon District", 38.72, -9.14, True),
    City("Porto", "Portugal", "Porto District", 41.15, -8.61, False),
    City("Moscow", "Russia", "Moscow Federal City", 55.76, 37.62, True),
    City("Saint Petersburg", "Russia", "Saint Petersburg", 59.93, 30.32, False),
    City("Novosibirsk", "Russia", "Novosibirsk Oblast", 55.01, 82.93, False),
    City("Riyadh", "Saudi Arabia", "Riyadh Region", 24.69, 46.72, True),
    City("Jeddah", "Saudi Arabia", "Makkah Region", 21.49, 39.19, False),
    City("Dammam", "Saudi Arabia", "Eastern Region", 26.43, 50.10, False),
    City("Pretoria", "South Africa", "Gauteng", -25.75, 28.19, True),
    City("Johannesburg", "South Africa", "Gauteng", -26.20, 28.05, False),
    City("Cape Town", "South Africa", "Western Cape", -33.93, 18.42, False),
    City("Durban", "South Africa", "KwaZulu-Natal", -29.86, 31.02, False),
    City("Madrid", "Spain", "Community of Madrid", 40.42, -3.70, True),
    City("Barcelona", "Spain", "Catalonia", 41.39, 2.17, False),
    City("Seville", "Spain", "Andalusia", 37.39, -5.98, False),
    City("Valencia", "Spain", "Valencia", 39.47, -0.38, False),
    City("Stockholm", "Sweden", "Stockholm County", 59.33, 18.07, True),
    City("Gothenburg", "Sweden", "Vastra Gotaland County", 57.71, 11.97, False),
    City("Bern", "Switzerland", "Canton of Bern", 46.95, 7.45, True),
    City("Zurich", "Switzerland", "Canton of Zurich", 47.38, 8.54, False),
    City("Geneva", "Switzerland", "Canton of Geneva", 46.20, 6.14, False),
    City("Bangkok", "Thailand", "Bangkok", 13.76, 100.50, True),
    City("Chiang Mai", "Thailand", "Chiang Mai Province", 18.79, 98.98, False),
    City("Ankara", "Turkey", "Ankara Province", 39.93, 32.86, True),
    City("Istanbul", "Turkey", "Istanbul", 41.01, 28.98, False),
    City("Izmir", "Turkey", "Izmir Province", 38.42, 27.13, False),
    City("Kyiv", "Ukraine", "Kyiv Oblast", 50.45, 30.52, True),
    City("Lviv", "Ukraine", "Lviv Oblast", 49.84, 24.03, False),
    City("Abu Dhabi", "United Arab Emirates", "Abu Dhabi", 24.45, 54.65, True),
    City("Dubai", "United Arab Emirates", "Dubai", 25.20, 55.27, False),
    City("Sharjah", "United Arab Emirates", "Sharjah", 25.34, 55.41, False),
    City("London", "United Kingdom", "England", 51.51, -0.13, True),
    City("Manchester", "United Kingdom", "England", 53.48, -2.24, False),
    City("Birmingham", "United Kingdom", "England", 52.49, -1.89, False),
    City("Edinburgh", "United Kingdom", "Scotland", 55.95, -3.19, False),
    City("Glasgow", "United Kingdom", "Scotland", 55.86, -4.25, False),
    City("Cardiff", "United Kingdom", "Wales", 51.48, -3.18, False),
    City("Belfast", "United Kingdom", "Northern Ireland", 54.60, -5.93, False),
    City("Washington D.C.", "United States", "Georgia", 38.90, -77.04, True),
    City("New York City", "United States", "New York", 40.71, -74.01, False),
    City("Los Angeles", "United States", "California", 34.05, -118.24, False),
    City("Chicago", "United States", "Illinois", 41.88, -87.63, False),
    City("Houston", "United States", "Texas", 29.76, -95.37, False),
    City("Phoenix", "United States", "California", 33.45, -112.07, False),
    City("Philadelphia", "United States", "Pennsylvania", 39.95, -75.17, False),
    City("San Francisco", "United States", "California", 37.77, -122.42, False),
    City("Seattle", "United States", "Washington", 47.61, -122.33, False),
    City("Boston", "United States", "Massachusetts", 42.36, -71.06, False),
    City("Miami", "United States", "Florida", 25.76, -80.19, False),
    City("Atlanta", "United States", "Georgia", 33.75, -84.39, False),
    City("Montevideo", "Uruguay", "Montevideo Department", -34.88, -56.17, True),
    City("Caracas", "Venezuela", "Capital District", 10.48, -66.90, True),
    City("Maracaibo", "Venezuela", "Zulia", 10.63, -71.63, False),
    City("Hanoi", "Vietnam", "Hanoi", 21.03, 105.85, True),
    City("Ho Chi Minh City", "Vietnam", "Ho Chi Minh City", 10.82, 106.63, False),
]


def get_all_cities() -> list[City]:
    return list(CITIES)


def get_cities_by_country(country: str) -> list[City]:
    return [c for c in CITIES if c.country.lower() == country.lower()]


def get_capital_cities() -> list[City]:
    return [c for c in CITIES if c.is_capital]


def get_city_by_name(name: str) -> City | None:
    for city in CITIES:
        if city.name.lower() == name.lower():
            return city
    return None


def get_all_regions() -> list[Region]:
    return list(REGIONS)


def get_regions_by_country(country: str) -> list[Region]:
    return [r for r in REGIONS if r.country.lower() == country.lower()]


def get_regions_by_continent(continent: str) -> list[Region]:
    return [r for r in REGIONS if r.continent.lower() == continent.lower()]
